### ISSUE TITLE
Android System WebView has stopped

### ISSUE THREAD

**Issue by aidengilmartin** [moezbhatti/qksms#1024]
App Version: 3.0.4 (Issue present on FDroid & Google Play variant)
Device: OnePlus 3 running LineageOS 15.1 (8.1.0 Oreo)

When opening a message thread the Android error dialog is displayed which states "Android System WebView has stopped". It gives you the option of opening the app again or muting until the device restarts.
If you dismiss the dialog everything works fine with no more error dialogues until the app is closed and reopened, where the dialog shows itself again.

Issue wasn't present in 2.7.3 and is present from 3.0.3+ (FDroid)

**Comment by realmain** [comment]
Confirmed, same issue on OnePlus 3T w/ Lineage OS 15.1 for microG

**Comment by Neyvermore** [comment]
Same issue on Xiaomi Mi A1 running CosmicOS. Haven't tried it on other roms yet.

**Comment by homersimpsons** [comment]
Doesn't have this problem on Xiaomi Mi A1 official ROM (Android 8.0.0, Security Patch: March 1, 2018)

**Comment by moezbhatti** [comment]
Can't seem to repro this on my own device - hopefully another dev might have some insight as to why this is happening

**Comment by purplg** [comment]
I also have this issue. It occurs whenever I open a specific conversation. Not sure what's so special about that conversation thread, but here's the error that is thrown:

```
E/asset: setgid: Operation not permitted
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.webview:sandboxed_process0, PID: 18908
    android.content.res.Resources$NotFoundException: Array resource ID #0x7f030007
        at android.content.res.Resources.obtainTypedArray(Resources.java:618)
        at android.content.res.Resources.preloadFonts(Resources.java:380)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5769)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.WebViewZygoteInit.main(WebViewZygoteInit.java:146)
```

Per searching and finding [this stackoverflow post](https://stackoverflow.com/questions/46112081/adview-causing-chrome-crash), I commented out the meta-data `preloaded_fonts` tag in the presentation manifest and the issue was resolved for me.

**Comment by moezbhatti** [comment]
Thanks for sharing! This is super helpful in fixing the crash.

**Comment by purplg** [comment]
I forgot to mention that this error only happens once per launch of the app. In order to reproduce this, I have to back out and swipe the app away, relaunch, and open that affected thread.

Lemme know if I can provide anymore information

**Comment by schneekluth** [comment]
Issue is no longer existent with latest 3.0.9. Kudos!

**Comment by realmain** [comment]
Still happens to me on 3.0.9

**Comment by moezbhatti** [comment]
It seems that this is fixed by updating to the latest version if [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview)

**Comment by realmain** [comment]
On LineageOS, I realized that I haven't updated my phone in a month, and I was on WebView v65.0.3325.144. I just updated my phone and now I'm on v66.0.335.9.117. This issue doesn't persist anymore.

**Comment by moezbhatti** [comment]
More info: A user on the latest version still experiencing the crash - https://www.reddit.com/r/Android/comments/8ekxiq/dev_qksms_is_back/dy0e5m1/?context=10000

**Comment by HorlogeSkynet** [comment]
Hi there !

Thanks for this wonderful app, and for having drawn out the v3 :stuck_out_tongue_winking_eye:

I can confirm it's happening with RR 6.0 (LineageOS 15.1, Oreo) with v3.0.9 (on OPO Bacon).

Bye :ok_hand:

**Comment by moezbhatti** [comment]
Another user reported it still occurring after updating to latest ASW

Version: 3.1.3
Device: OnePlus ONEPLUS A3003
SDK: 27

**Comment by Snappiestjack** [comment]
Hi there,

App version: 3.1.3
Webview version: 66.0.3359.158
Device: OnePlus 3T
ROM: Lineage OS 15.1

Seen above that updating to latest webview seemed to fix this issue, I was on an older version, but after updating issue is still present. 

Happens on all message threads after a cold start.

**Comment by seriosbrad** [comment]
I was just having this issue with 3.2.0.

Installing WebView from the play store and switching to it (66.0.3359.158) fixed it.

**Comment by moezbhatti** [comment]
This seems to have been resolved with the more recent versions of ASW

**Comment by moezbhatti** [comment]
Looks like it was still happening for certain users, and I believe I found a fix.

I was able to reproduce the issue by running an Android emulator running Oreo, and disabling Chrome. Then the ASW crash dialog would show when a conversation is opened

I found [this comment](https://stackoverflow.com/a/49244598) on StackOverflow which mentions that the system uses ASW in order to linkify locations in TextViews, and with certain phone configurations this can cause a crash.

I was able to fix this by removing the autoLink for maps in the message TextViews in a646291c51707ed9d0e582021b0d965c564094e6

**Comment by HorlogeSkynet** [comment]
You're right, it was still happening for users, let's say, running old vendor packages.
Looking forward to trying your fix. I'll keep you posted 👍
Thanks again for your work 👌

**Comment by moezbhatti** [comment]
@HorlogeSkynet here's a test APK - if you could verify that it works for you, that would be really great!

Note that it's a zip because Github currently doesn't allow uploading APKs

[presentation-noAnalytics-universal-release.apk.zip](https://github.com/moezbhatti/qksms/files/2285767/presentation-noAnalytics-universal-release.apk.zip)

**Comment by HorlogeSkynet** [comment]
Sorry installation keeps aborting, and logs are talking about a problem with a missing temp file...

**Comment by moezbhatti** [comment]
Hmm, it's possible you might to uninstall your existing version of QKSMS before it'll let you install that build. You'll end up losing all of your settings if you do this, so if that's too much of a hassle, don't worry about it!

**Comment by HorlogeSkynet** [comment]
Hmmmf... Logs were telling it ignores the signature mismatch though :thinking: 
When can we expect the next F-Droid release including this very commit ? Or maybe you wanted a test before and that was the point ?

**Comment by moezbhatti** [comment]
Hmm, AFAIK, it's not possible to install an APK if the signature doesn't match, without uninstalling the old version.

Anyway, yeah, it'll be included in the next update. Sharing the APK was mostly just to get a secondary confirmation, but it's not necessary :)

**Comment by sanjeebguru** [comment]
Try removing the below in AndroidManifest.xml

        <meta-data-->
           android:name="preloaded_fonts"
            android:resource="@array/preloaded_fonts" />
