### ISSUE TITLE
MMS notification if data is disabled

### ISSUE THREAD

**Issue by ToNIX-** [moezbhatti/qksms#118]
If data is disabled, it would be a nice feature to have a notification (if possible from the contact sending the MMS) that a new MMS is ready to download.

Once data is enabled, you could touch this message to download the MMS.

**Comment by ToNIX-** [comment]
Bumping this, any news about this request?

**Comment by moezbhatti** [comment]
Sorry, haven't had a chance to work on this personally yet

**Comment by ToNIX-** [comment]
@moezbhatti Thanks for the feedback, it's unfortunately preventing me (and potentially lots of users) of using QKSMS.

**Comment by kolAflash** [comment]
Currently, if I receive an MMS while data is disabled, there is no way to get notified. (I only know there's an MMS waiting because myself send it from another phone)

Additionally, if reenabling data, I either have to restart my phone of force-close and reopen the QKSMS app to receive the MMS.

Related: https://github.com/qklabs/qksms/issues/153

Additionally QKSMS should warn when sending an MMS while data is disabled, so the MMS can't be send.

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0

**Comment by fengshaun** [comment]
I'm on 3.6.3 and this is still an issue. I don't get any notification for MMS when data is turned off.

**Comment by OhSoGood** [comment]
+1 for this feature. It is present in the raw Android SMS app, and I know several people who don't have data/4G premanently on who pitifully don't / cannot use QKSMS because of this.

**Comment by njean42** [comment]
+1 for this feature, for the same reasons given by others :)

**Comment by fengshaun** [comment]
It seems this issue is at the bottom of priorities and I was just notified that I missed a few important messages from colleagues. Where would I look (file, module, function, etc) to add this functionality? How is the code generally structured in terms of detecting arrival of sms/mms and adding it to db? just a short primer will do. Thanks.

**Comment by moezbhatti** [comment]
This file is the entry point for incoming MMS: https://github.com/moezbhatti/qksms/blob/master/data/src/main/java/com/moez/QKSMS/receiver/MmsReceiver.kt

Note that this is definitely not at the end of the list of priorities, I actually moved it up to a specific upcoming release a few weeks ago. It's a very complicated feature to build, as it touches a lot of different parts of the app (native MMS content provider, QKSMS' internal database, UI), but I'm planning to get to it by the end of this year

**Comment by fengshaun** [comment]
Thanks, I understand it'll take a long time as a solo dev, so I'll see what I can do to help.

**Comment by OhSoGood** [comment]
@moezbhatti : end of year? Yes, that will be Christmas present!!! Thank you to listen to our queries!

**Comment by afish** [comment]
Any update on this?

**Comment by moezbhatti** [comment]
Unfortunately not, but this is definitely one of the most important things I plan to work on in the near future

**Comment by afish** [comment]
Great! Any ideas how much easier would it be to fix storing MMS in native content provider (so it can be downloaded by other apps) without implementing all the other parts? Thanks to that messages wouldn't be lost anymore.

**Comment by moezbhatti** [comment]
Actually, that already does happen. The problem is that most messages have an expiry of either 1 day or 1 week (usually), so in many cases the messages will still get lost

**Comment by afish** [comment]
No, it does not. I have just tested with the latest version from the Google Play and MMS sent few minutes ago. Application does add a message to the native store so I can see a placeholder in other apps (like Messages from Google) but I cannot download it. However, if I set Google Messages to be the default SMS app, turn the data connection off and send another MMS, then I can see the placeholder and I can download the message after turning the data on. There is something wrong with QKSMS.

**Comment by afish** [comment]
I don't know how useful this may be, but when I use Xiaomi built-in messaging app to download an MMS stored by QKSMS when the phone was offline, I'm getting this:

```
Couldn't download message (No subject) from user
```

Does ```No subject``` ring abell? Is it something QKSMS should set but does not?

**Comment by quilicicf** [comment]
Hi, 

I'm using QKSMS 3.7.10 (it's included in /e/) and have the mobile data turned off 99% of the time (I use automation tools to connect to data every few hours instead of always, saves A LOT of battery).

This means I'm not aware when I get a new MMS and since my automation tool prefers WIFI over mobile data I sometimes miss them altogether.

I'd be willing to help if I can,

**Comment by pl6025** [comment]
On android 10 (xiaomi mi a3), I've a notification about mms and I need to do something (not really clear and it never works). At this moment I know that I've missed a MMS.
I put data on
I open stock messag app. It wants to be my default app.
I click on download button to received my MMS.
I open QK SMS (3.8.1 from F-Droid) and configure it as default app.

It will be very good for this app to have it natively, because lot of people won't go back to QK SMS after changing their default app.

**Comment by ghost** [comment]
This is still an issue in 2024, doesnt work well on google messages compared to samsung, I just want reliable messaging apps, so hard in 2024
