### ISSUE TITLE
BUG: Support starting a conversation with E.123 internaltional phone number format (that with the leading +)

### ISSUE THREAD

**Issue by andidevi** [moezbhatti/qksms#1198]
### DESCRIPTION

If you start a new conversation and use the phone number in the E.123 international format with leading + you can't send the first message. Additionally, it seems that on Android 8 first messages of new conversations will not be received, too. 

### STEPS
1. Make sure the other party is able to receive messages, but you do _not_ have any single message stored of any conversation with that party on your phone.
2. Open QKSMS and start a new conversation 
3. Enter the recipients phone number in the E.123 international format with leading +
https://en.wikipedia.org/wiki/E.123
4. type some text
5. press send and see that it does nothing

### OBSERVATIONS

See that the pressing send does nothing.

After that, ask the other party to send you some sms. the dialog will not show up in QKSMS. If you switch to Google Messages or the standard sms app. You will be able to send and receive messages.
After that, QKSMS will work as expected.### OBSERVATIONS

### EXPECTED
QKSMS is able to send and receive the very first message without help from any other app even if you use the E.123 international format.

QKSMS will show you some error message instead of silently refusing to send a message, if it is not happy with the recipients phone number. This is important, as this bug happens with known contacts, too.

**Comment by moezbhatti** [comment]
@andidevi what phone are you using?

**Comment by andidevi** [comment]
Huawei P20 with Android OS 8.1.0.128, but I had similiar problems with Vernee Mix 2 on Android 7.0 ("VOS 1.0.0").

The difference is, that the Huawei does not read new messages even if the conversation is there, but this could be #1200 

I'm using qkSMS 3.3.2 (and I'm able to build a spefic version to test)

**Comment by moezbhatti** [comment]
@andidevi can you try building the latest dev branch and see if that fixes the issue for you? I believe that 52c99faed130c3dcce899983e24cb6354da06e98 should fix this

**Comment by KruziikG** [comment]
@moezbhatti I have build version 52c99fa, but both this version and release 3.3.2 are able to send message to +86 xxxxxxxxxxx number. But I still cannot get a new message in inbox if I don't have a conversion 
 with this number privously. see my issue https://github.com/moezbhatti/qksms/issues/1200

**Comment by andidevi** [comment]
I got the following lint errors with e416b6d85f44cadb8aa97806b7d97487d39548e8
  
  /P/A/qksms/data/src/main/java/compat/SubscriptionManagerCompat.kt:35: Error: Missing permissions required by SubscriptionManager.getActiveSubscriptionInfoList: android.permission.READ_PHONE_STATE [MissingPermission]
                  subscriptionManager?.activeSubscriptionInfoList?.map { SubscriptionInfoCompat(it) } ?: listOf()
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /P/A/qksms/data/src/main/java/repository/MessageRepositoryImpl.kt:245: Error: Method reference requires API level 22 (current min is 21): android.telephony.SmsManager::getSmsManagerForSubscriptionId [NewApi]
                  ?.let(SmsManager::getSmsManagerForSubscriptionId)
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

where [MissingPermission] may be a useful hint.

However it seems that the messages got sended out, but the conversation has not been added to the inbox. 

I had to use Google Messages to look for the sended sms and to have it added to the index. Only after that the conversation is shown in qksms inbox.

**Comment by andidevi** [comment]
while sending is ok now,
it also did not read the incoming answer (with having the previous conversation removed before).

Google Messages is showing it, but in qkSMS it is missing it.

I could force qksms to read the new messages by switching to Google Messages as default sms app and back again. qkSMS only read the messages in the single moment after it became the default sms app.

**Comment by andidevi** [comment]
Please close, this is fixed in 3.3.4 27b6d3ff57aa444d27a3e2d0bdd51850cdb3671b
Thanks!
