### ISSUE TITLE
Sharing to new conversation doesn't display name/number

### ISSUE THREAD

**Issue by Jrdnkasparek** [moezbhatti/qksms#1211]
When you go into the contacts app, click on a contact, and select text it will open qksms but it asks who you want to send it to

**Comment by spocko** [comment]
It looks like this issue was introduced in version 3.3.3, and is fixed in version 3.3.4.

There is a related issue though:
When a text is initiated via the contacts app, the contact name/number is not displayed at the top of the screen unless there is an existing conversation with that contact.

**Comment by Jrdnkasparek** [comment]
This was fixed in 3.3.4, sorry for the delayed responce

**Comment by moezbhatti** [comment]
Going to reopen this because there's still a slight issue remaining with this
