### ISSUE TITLE
Tapping a notification takes you to wrong conversation

### ISSUE THREAD

**Issue by jnns** [moezbhatti/qksms#405]
### DESCRIPTION

A notification does not take the user to the corresponding conversation. 
### STEPS
1. Open up a conversation with person A in QKSMS
2. Wait until your display switches off and your phone becomes locked
3. Wait until a new SMS from person B arrives
4. Tap on the body of the notification (not the buttons) or drag down the notification to open it
### EXPECTED

You're taken to the conversation with person B
### OBSERVATIONS

The conversation with person A is displayed instead.

Maybe related to #73.

**Comment by moezbhatti** [comment]
Fixed in version 2.6

**Comment by kkwaiser** [comment]
This bug is still present in version 2.6.3 (Samsung SM-G900v running Android 5.0 )

**Comment by moezbhatti** [comment]
@kkwaiser is this happening every time, or seemingly randomly?

**Comment by kkwaiser** [comment]
@moezbhatti It happens every time.

**Comment by moezbhatti** [comment]
@kkwaiser when you've tried it was the app already running in the background? Or was it closed?

**Comment by kkwaiser** [comment]
@moezbhatti - I follow the steps in the OP to reproduce, the app was running in the foreground when the screen was locked. I don't know if it is in the background/foreground when the screen is locked.

**Comment by fresheneesz** [comment]
For me this happens a lot, but I'm not sure if its "every time". I'm trying to repro by marking a conversation unread, going to another conversation, then opening the notification, but this doesn't seem to repro the problem. I'll have to wait to get another real notification for a new message to see if it happens consistently.

**Comment by kobiyashi** [comment]
Whenever I open from notification, it goes to the last conversation opened, not the one the notification is for. This happens every time.

**Comment by fresheneesz** [comment]
I'm seeing the same thing as kobiyashi. If I mark a conversation unread, this doesn't happen. But with a notification for a real new message, it seems to always go to the last conversation I had open.

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0
