### ISSUE TITLE
Sync message when sent from another app

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#906]
If a message is sent from Pushbullet or Google Assistant, then it is added to the default SMS database but not QKSMS' internal database, resulting in it not being displayed unless the database is re-synced.

**Comment by moezbhatti** [comment]
Fixed in f70cd965a75b7ff02385809b68b1a1050033f6d0

**Comment by spocko** [comment]
It looks like this fix was included in version 3.0 beta 6, but I'm still having the same problem with version 3.3.2. 

Example:
1) Send a sms via Pushbullet on a PC (using the native Pushbullet client for Windows)
2) Look at conversation in Samsung Messages. The new message is there.
3) Look at conversation in QKSMS. The new message is not there.
4) Resync QKSMS. Now the new message is there.

**Comment by spocko** [comment]
Looking at the commit referenced above, I see a comment in SmsProviderChangedReceiver.kt saying "This only works on API 24+". My device has Android 6.0, API level 23, so I guess that explains why I'm still seeing the problem.

QKSMS is currently the default messenger on my phone, but I also have Android Messages, Pulse, Textra, Samsung Messages, and YAATA installed. In the example from my last post, QKSMS was the only one that did not show the new message automatically, so there must be a solution that works on older Android versions.

**Comment by moezbhatti** [comment]
@spocko you're right, thanks for catching that. A solution needs to be worked on for API 23 and below

**Comment by lmo-reira** [comment]
Same problem here with Android 5.1.1 and Qksms 3.5.3.

I'm sending sms from my computer using Project MAXS.

Synch does bring back the sent sms into Qksms, otherwise I only have the received messages.

**Comment by moezbhatti** [comment]
This seems to be happening as well when sending messages from Microsoft's Your Phone app
